### ISSUE TITLE
DefaultExceptionHandler

### ISSUE THREAD

**Issue by ejemba** [sn3d/lime-mvc#1]
Hello There,

when trying to configure a default exceptionhandler like this (like describe in the wiki)

  bind(ExceptionHandler.class).annotatedWith(Names.named(ExceptionResolver.DEFAULT_EXCEPTIONHANDLER_NAME)) 
        .toInstance(new NetAppExceptionHandler()); 

I have the following exception 

com.google.inject.CreationException: Guice creation errors:

1) A binding to org.zdevra.guice.mvc.ExceptionHandler annotated with @com.google.inject.name.Named(value=defaultExceptionHandler) was already configured at org.zdevra.guice.mvc.MvcModule.configureServlets(Unknown Source).

Seems a bug to me, we can't redefine the defaut exception handler.

I'm using version 0.4.0 of lime-mvc. 

Thanks

**Comment by sn3d** [comment]
Yeah definitely it's bug. Problem is with multiple binding in Guice. I'll fix it. Until then there is workaround: Just register your exception handler to Exception.class. 

class YourModule extends MvcModule {
   protected void configureControllers() {
      ...
      bindException(Exception.class).toHandler(NetAppExceptionHandler.class);
   }
}

I guess it should help.

**Comment by sn3d** [comment]
I want to fix it and add some checking where default handler is binded only when user doesn't bind it but Guice doesn't offer me any approach how to check whether something is binded. I try to get the provider but this was not 100% working solution. Fortunately Guice offers the module overriding which can solve the problem (http://google-guice.googlecode.com/git/javadoc/com/google/inject/util/Modules.html).
