### ISSUE TITLE
Mavenization

### ISSUE THREAD

**Issue by sn3d** [sn3d/lime-mvc#6]
Current build is horrible. Because project is distributed mostly via OSS maven repositories, I would like refactor the project to regular maven project.

**Comment by tadas-subonis** [comment]
I was in the middle of making a lightweight mvc (actually extracting from existing project) until I found this project of yours... I would be up to this mavenization task :). Shouldn't take long for me :)

**Comment by sn3d** [comment]
Hi,

Many thanks. Feel free to mavenize it. I'll commit your changes then and of course put you as a contributor. Right now I'm little busy with end of the world :) 

Anyway small info. It's easy task but unfortunately I did really ugly tests :( The tests might be little-bit tricky.I though I'll delete all these ugly tests and replace them by new tests. 

Also one small note. Currently in oss.sonatype.org there are 4 artefacts related to Lime. It's lime, lime-velocity, lime-freemarker and lime-jsilver. The project poms should look like:

org.zdevra:lime-parent (pom)
- org.zdevra:lime (jar)
- org.zdevra:lime-velocity (jar)
- org.zdevra:lime-jsilver (jar)
- org.zdevra:lime-freemarker (jar)

Good inspiration for POMs is of course Google Guice itself :)

**Comment by sn3d** [comment]
solved in issue #7
